#!/bin/bash

sxhkd &

INTERNAL_MONITOR="LVDS-1"
EXTERNAL_MONITOR="VGA1"

xrandr --output $INTERNAL_MONITOR --primary --mode 1024x768 --pos 0x0 --rotate normal

# dual monitor

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then

  xrandr --output $EXTERNAL_MONITOR --mode 1920x1080 --left-of LVDS1 --rotate normal

  bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 10
  bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"

  polybar vga &
else bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9
fi

bspc config split_ratio             0.62
bspc config top_padding             19
bspc config left_padding            0
bspc config right_padding           0
bspc config bottom_padding          0
bspc config window_gap              0

bspc config focus_follows_pointer	false
bspc config pointer_modifier	    mod1

bspc config automatic_scheme        spiral
bspc config focused_border_color    "#ffffff"
bspc config normal_border_color     "#222222"

polybar main &
picom &
setxkbmap gb &
feh --bg-center ~/.setup/walls/wall.png
